more afterburn options

diff --git a/bin/afterburn_path b/bin/afterburn_path
--- a/bin/afterburn_path
+++ b/bin/afterburn_path
@@ -1,6 +1,7 @@
 #!/bin/bash
 if [[ "$1" == --help || "$1" == -h ]] ; then
-  echo "USAGE: ${0##*/} [-h|--help] [-v] [--lib] [--cleanup|--restore] \$PATH|\$LD_LIBRARY_PATH|\$LIBPATH (arguments are order dependent)" 1>&2
+  echo "USAGE: ${0##*/} [-h|--help] [-v] [--lib] [--cleanup|--restore] [maxdirsize] \$PATH|\$LD_LIBRARY_PATH|\$LIBPATH (arguments are order dependent)" 1>&2
+  echo "       version = 1.0.0 2015/01/20"  1>&2
   exit 0
 fi
 [[ -x ${TMPDIR}/bin/link_files_in_dir ]] || exit 1
